[package]
name = "pyru"
version = "0.0.1"
authors = ["Said van de Klundert"]

[lib]
name = "pyru"
crate-type = ["dylib"]

[dependencies]
libc = "~0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
